// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBTnF5Y-dT9DEZnby7kvf_dD-ASk-cPAU',
    appId: '1:958310379776:web:e6f1cceaac85d55e98c3e5',
    messagingSenderId: '958310379776',
    projectId: 'fir-practice-1f6ed',
    authDomain: 'fir-practice-1f6ed.firebaseapp.com',
    storageBucket: 'fir-practice-1f6ed.appspot.com',
    measurementId: 'G-Z5B9VD8SGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkEQC4dIDpw3uXqHejrsxKW77vXJo4hg',
    appId: '1:958310379776:android:7591c58f1f1a39bb98c3e5',
    messagingSenderId: '958310379776',
    projectId: 'fir-practice-1f6ed',
    storageBucket: 'fir-practice-1f6ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6wagIdRNVTMpFR1kG7H1PrELePaBqss',
    appId: '1:958310379776:ios:e6ecfd875587e9fe98c3e5',
    messagingSenderId: '958310379776',
    projectId: 'fir-practice-1f6ed',
    storageBucket: 'fir-practice-1f6ed.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6wagIdRNVTMpFR1kG7H1PrELePaBqss',
    appId: '1:958310379776:ios:45d7801694ecb18e98c3e5',
    messagingSenderId: '958310379776',
    projectId: 'fir-practice-1f6ed',
    storageBucket: 'fir-practice-1f6ed.appspot.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
